# Generated by Django 5.0.4 on 2024-06-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dateOfBirth', models.CharField(max_length=225)),
                ('profession', models.CharField(max_length=225)),
                ('experience', models.CharField(max_length=225)),
                ('about', models.CharField(max_length=225)),
                ('telegram', models.CharField(max_length=225)),
                ('whatsapp', models.CharField(max_length=225)),
                ('vk', models.CharField(max_length=225)),
                ('instagram', models.CharField(max_length=225)),
            ],
        ),
    ]
